project:
  type: website
  output-dir: docs

website:
  title: "Neha_DSPG24_Blog"
  navbar:
    right:
      - href: about_Neha.qmd
        text: About
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
      - icon: linkedin
        href: https://www.linkedin.com/in/neha-tirunagiri/
format:
  html:
    theme: cosmo
    css: styles.css


